services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - "./backend:/app"
    working_dir: /app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    depends_on:
      database:
        condition: service_healthy
  frontend:
    image: node
    ports:
      - 5173:5173
    volumes:
      - "./frontend:/app"
    working_dir: /app
    command: bash -c "npm install -g npm && npm install && npm run dev -- --host 0.0.0.0"
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
