services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - "./backend:/app"
      - "./.env:/app/.env"
    working_dir: /app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    depends_on:
      database:
        condition: service_healthy
  frontend:
    image: node
    ports:
      - 5173:5173
    volumes:
      - "./frontend:/usr/src/app"
      - "./.env:/usr/src/app/.env"
    working_dir: "/usr/src/app"
    command: bash -c "npm install && npm run dev"
  database:
    image: postgis/postgis
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  dbconaf:
    image: postgis/postgis
    environment:
      - POSTGRES_PASSWORD=${DB_CONAF_PASSWORD}
      - POSTGRES_DB=${DB_CONAF_NAME}
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    ports:
      - 5432:5432
