// Content.tsx

import React from 'react';
import './ContentStyle.css';

const Content: React.FC = () => {
  return (
    <div className="content">
      {/* Contenido principal */}
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed velit libero, tempus sit amet dignissim ac, laoreet ac metus. Nulla pretium rhoncus est, ut eleifend libero finibus elementum. Sed sapien quam, hendrerit id nunc nec, condimentum eleifend leo. Vivamus ac egestas massa. Donec sollicitudin felis sapien, commodo bibendum mauris bibendum at. Ut sed risus in elit tincidunt accumsan non sed massa. Nam at sapien nunc.

                Duis vel mauris tincidunt, feugiat urna a, hendrerit enim. Nam sit amet nunc dolor. Cras lacinia elementum enim id eleifend. Praesent lacinia, neque nec luctus lobortis, nibh urna euismod metus, eleifend tempor tortor nisi et erat. Duis sed mattis ex, in accumsan nisi. Donec finibus, turpis vel rhoncus commodo, felis quam euismod dolor, sit amet auctor est neque pharetra felis. Etiam hendrerit tortor metus, non gravida est consectetur ac. Cras at erat in metus consequat placerat vitae scelerisque erat. Curabitur feugiat sem consequat vehicula egestas. Nullam aliquet augue at elit fringilla, quis mollis lacus tempor.
                
                Duis dictum nulla mi, quis tempus turpis sollicitudin sit amet. Nulla quis sem nisi. Vestibulum pulvinar sapien eu suscipit dapibus. Fusce nisl massa, faucibus in dignissim eget, tincidunt nec est. Etiam bibendum porta libero vitae maximus. Sed condimentum ante orci, laoreet feugiat odio ornare in. Ut mollis, lorem a bibendum tempor, sapien dui faucibus ligula, vitae congue purus tellus ac justo. Pellentesque elementum tortor id hendrerit vulputate. In consequat, sem nec ullamcorper sagittis, nibh elit mattis dui, varius porttitor ligula massa mollis elit. Ut sed sapien vel mauris iaculis mollis sed a felis. Vivamus at sollicitudin massa.
                
                Sed aliquet rutrum nulla. Nullam volutpat enim vitae lectus feugiat sagittis. Etiam vel elementum leo. Curabitur at turpis bibendum, placerat purus quis, gravida leo. Nulla pulvinar sit amet magna non sagittis. Mauris ullamcorper placerat nisl nec porta. Aliquam odio arcu, venenatis non metus nec, porttitor pellentesque leo. Vestibulum sapien nibh, accumsan eu dapibus et, tempus in nunc. Nullam ullamcorper interdum risus in rhoncus. Nulla finibus neque a elementum auctor.
                
                Etiam ut condimentum diam, accumsan auctor mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed at orci auctor erat ultricies condimentum et congue turpis. Donec viverra tortor et scelerisque viverra. Duis convallis rhoncus ultrices. Aliquam porta magna eu est ultrices faucibus. Fusce sed orci quis nibh cursus vestibulum vel vel est. Praesent pretium diam tellus, nec pretium tortor porttitor eget. Cras quis leo risus. Duis arcu arcu, egestas ut tincidunt id, sodales id augue. Praesent sed lobortis sem, vel laoreet ante. Vestibulum sagittis est ac sem iaculis suscipit. Suspendisse bibendum turpis tincidunt ligula consectetur, vel gravida felis accumsan. Phasellus a sem dapibus, finibus ipsum vitae, pretium mi. Etiam lorem urna, varius sed nisi eu, convallis hendrerit sem.
                
                Donec convallis sem elit, id dapibus tellus iaculis sagittis. Aliquam at pellentesque dolor, eget aliquam lorem. Donec sed odio purus. Vestibulum suscipit maximus venenatis. Phasellus eget lorem nibh. Sed justo felis, malesuada vitae imperdiet at, dapibus eget purus. Fusce aliquam elit quam, vel dictum mi mollis a. Curabitur iaculis nulla a risus semper, ut venenatis enim egestas. Vestibulum vulputate sem a tempus lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam efficitur, mi at suscipit gravida, dui mi accumsan quam, ut venenatis nisi ligula in nulla. Praesent lacinia leo sed finibus ornare.
                
                Aenean facilisis nunc et tellus laoreet, sit amet vehicula justo condimentum. Phasellus in rhoncus sem. Vivamus laoreet maximus risus ac semper. Sed ac leo at magna volutpat viverra. Sed quis tincidunt metus. Sed malesuada in nulla vitae hendrerit. Morbi turpis leo, interdum eget laoreet at, convallis eget elit. Aenean id lectus non dui hendrerit malesuada et a lectus. Donec dictum rhoncus lectus et fermentum. Mauris bibendum condimentum est, id lacinia odio. Mauris sed suscipit urna.
                
                Sed consequat pretium risus, id pellentesque velit. Aenean sit amet erat placerat, aliquet ante sed, consequat magna. Curabitur nec ante aliquam, pellentesque metus sit amet, commodo dui. Cras suscipit venenatis pulvinar. Etiam egestas cursus bibendum. Etiam interdum tempor ipsum id finibus. Aenean elementum mi quis neque fringilla facilisis. Mauris ullamcorper, sapien ut accumsan varius, lorem nibh tempus leo, non luctus quam massa quis neque. Nam sed metus et nulla lobortis rhoncus nec fermentum ipsum. Donec ornare dignissim sollicitudin. Donec ultrices augue ac interdum iaculis. Duis pretium erat nec erat hendrerit congue. Praesent vel eleifend metus. Phasellus sed placerat mauris, ut viverra arcu.
                
                Nulla ac sagittis mauris. Nam condimentum, mauris a commodo ornare, ligula nulla lobortis dolor, a ullamcorper lorem nisl nec purus. Vivamus eleifend, arcu nec vulputate varius, est eros facilisis lorem, nec dapibus augue sem vitae libero. Nunc pretium rhoncus lectus sed auctor. Proin congue et lectus rutrum volutpat. Integer iaculis volutpat volutpat. Etiam est odio, accumsan ac orci vitae, vestibulum vehicula massa. Nulla eget mauris sit amet enim laoreet dapibus ut et tellus.
                
                Vivamus in nisl aliquam, sodales libero non, pretium purus. Ut in lacinia justo. Morbi blandit lacus posuere ante vehicula, ac sagittis diam sagittis. Vestibulum at rhoncus nisi, ut tempus turpis. Nullam nec odio elit. Ut non aliquam diam. Praesent condimentum, ante at posuere mollis, mi massa sollicitudin ante, ut laoreet tellus urna nec magna.
                
                Sed pharetra erat et justo convallis vehicula. Vestibulum efficitur ut velit sit amet molestie. Praesent fermentum eleifend urna ac lacinia. Praesent dignissim felis nisi, vitae porta augue rhoncus ut. Ut est ligula, interdum et mi non, semper imperdiet enim. Fusce rutrum mi et vulputate pellentesque. Quisque augue nulla, porta in malesuada at, blandit vel metus.
                
                Donec nec suscipit mauris, sed mattis ex. Sed euismod vel elit sed lacinia. Mauris fermentum lorem at lobortis ullamcorper. Proin a lectus et nibh facilisis finibus. Phasellus ligula magna, ullamcorper at arcu pulvinar, cursus vulputate enim. Cras euismod, tellus id accumsan placerat, mauris risus ultricies magna, sed vestibulum urna enim pretium nisl. Maecenas tempus rhoncus tempor. Donec quis convallis tortor. Cras accumsan ultricies efficitur. Maecenas rutrum gravida arcu eget venenatis. Duis tortor turpis, consequat a ipsum ut, feugiat suscipit ex. Proin suscipit diam eget faucibus tempor. Duis a magna ac ipsum venenatis condimentum.
                
                Ut cursus diam vel consequat hendrerit. Proin tellus justo, tempor et ipsum id, bibendum euismod neque. Fusce nunc odio, hendrerit nec faucibus sed, malesuada non augue. Morbi tempus feugiat nulla eget lacinia. Sed id massa non ex tincidunt rhoncus a sit amet nunc. Integer ornare tortor suscipit dignissim lobortis. Duis magna nunc, interdum a neque non, volutpat elementum mi. Duis urna elit, tempus sed aliquet eu, blandit dictum magna. Praesent scelerisque, est a mollis sodales, mauris felis aliquam ligula, a convallis velit velit at erat. Maecenas et ante augue. In hac habitasse platea dictumst. Proin dignissim ex sit amet ligula gravida, a congue massa tempor. Donec molestie nunc vitae felis porta, vitae tempor eros finibus.
                
                Aenean ut justo eget leo aliquet aliquet vel et justo. Nulla tristique porta dui et cursus. Etiam vel rhoncus sem. Nullam tristique id sem quis blandit. Proin et pharetra ligula. Vestibulum rhoncus nisi mi, eget hendrerit nisi malesuada a. Nunc ante ante, dignissim nec augue quis, cursus venenatis lacus. Ut efficitur, magna ut faucibus semper, risus odio cursus eros, eu laoreet quam orci vel ipsum. Pellentesque sagittis tortor ac lacus dapibus lacinia. Donec convallis quam nisi, non sollicitudin odio egestas vitae. Etiam erat tellus, pellentesque at vestibulum vel, pellentesque at erat. Sed sit amet urna eu ante faucibus placerat. Maecenas a ligula et libero ultrices dignissim.
                
                Donec dictum, ante sit amet commodo sodales, est eros sollicitudin arcu, vitae facilisis enim lectus ut lorem. Integer feugiat mauris hendrerit gravida scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris ornare nibh sit amet rhoncus dictum. Fusce id diam luctus, lobortis sem convallis, hendrerit nisi. Sed non placerat massa, at porta risus. Nunc hendrerit nunc et mattis accumsan. Nam cursus sapien magna, pulvinar eleifend dolor congue eu.
                Phasellus in rhoncus sem. Vivamus laoreet maximus risus ac semper. Sed ac leo at magna volutpat viverra. Sed quis tincidunt metus. Sed malesuada in nulla vitae hendrerit. Morbi turpis leo, interdum eget laoreet at, convallis eget elit. Aenean id lectus non dui hendrerit malesuada et a lectus. Donec dictum rhoncus lectus et fermentum. Mauris bibendum condimentum est, id lacinia odio. Mauris sed suscipit urna.
                
                Sed consequat pretium risus, id pellentesque velit. Aenean sit amet erat placerat, aliquet ante sed, consequat magna. Curabitur nec ante aliquam, pellentesque metus sit amet, commodo dui. Cras suscipit venenatis pulvinar. Etiam egestas cursus bibendum. Etiam interdum tempor ipsum id finibus. Aenean elementum mi quis neque fringilla facilisis. Mauris ullamcorper, sapien ut accumsan varius, lorem nibh tempus leo, non luctus quam massa quis neque. Nam sed metus et nulla lobortis rhoncus nec fermentum ipsum. Donec ornare dignissim sollicitudin. Donec ultrices augue ac interdum iaculis. Duis pretium erat nec erat hendrerit congue. Praesent vel eleifend metus. Phasellus sed placerat mauris, ut viverra arcu.
                
                Nulla ac sagittis mauris. Nam condimentum, mauris a commodo ornare, ligula nulla lobortis dolor, a ullamcorper lorem nisl nec purus. Vivamus eleifend, arcu nec vulputate varius, est eros facilisis lorem, nec dapibus augue sem vitae libero. Nunc pretium rhoncus lectus sed auctor. Proin congue et lectus rutrum volutpat. Integer iaculis volutpat volutpat. Etiam est odio, accumsan ac orci vitae, vestibulum vehicula massa. Nulla eget mauris sit amet enim laoreet dapibus ut et tellus.
                
                Vivamus in nisl aliquam, sodales libero non, pretium purus. Ut in lacinia justo. Morbi blandit lacus posuere ante vehicula, ac sagittis diam sagittis. Vestibulum at rhoncus nisi, ut tempus turpis. Nullam nec odio elit. Ut non aliquam diam. Praesent condimentum, ante at posuere mollis, mi massa sollicitudin ante, ut laoreet tellus urna nec magna.
                
                Sed pharetra erat et justo convallis vehicula. Vestibulum efficitur ut velit sit amet molestie. Praesent fermentum eleifend urna ac lacinia. Praesent dignissim felis nisi, vitae porta augue rhoncus ut. Ut est ligula, interdum et mi non, semper imperdiet enim. Fusce rutrum mi et vulputate pellentesque. Quisque augue nulla, porta in malesuada at, blandit vel metus.
                
                Donec nec suscipit mauris, sed mattis ex. Sed euismod vel elit sed lacinia. Mauris fermentum lorem at lobortis ullamcorper. Proin a lectus et nibh facilisis finibus. Phasellus ligula magna, ullamcorper at arcu pulvinar, cursus vulputate enim. Cras euismod, tellus id accumsan placerat, mauris risus ultricies magna, sed vestibulum urna enim pretium nisl. Maecenas tempus rhoncus tempor. Donec quis convallis tortor. Cras accumsan ultricies efficitur. Maecenas rutrum gravida arcu eget venenatis. Duis tortor turpis, consequat a ipsum ut, feugiat suscipit ex. Proin suscipit diam eget faucibus tempor. Duis a magna ac ipsum venenatis condimentum.
                
                Ut cursus diam vel consequat hendrerit. Proin tellus justo, tempor et ipsum id, bibendum euismod neque. Fusce nunc odio, hendrerit nec faucibus sed, malesuada non augue. Morbi tempus feugiat nulla eget lacinia. Sed id massa non ex tincidunt rhoncus a sit amet nunc. Integer ornare tortor suscipit dignissim lobortis. Duis magna nunc, interdum a neque non, volutpat elementum mi. Duis urna elit, tempus sed aliquet eu, blandit dictum magna. Praesent scelerisque, est a mollis sodales, mauris felis aliquam ligula, a convallis velit velit at erat. Maecenas et ante augue. In hac habitasse platea dictumst. Proin dignissim ex sit amet ligula gravida, a congue massa tempor. Donec molestie nunc vitae felis porta, vitae tempor eros finibus.
                
                Aenean ut justo eget leo aliquet aliquet vel et justo. Nulla tristique porta dui et cursus. Etiam vel rhoncus sem. Nullam tristique id sem quis blandit. Proin et pharetra ligula. Vestibulum rhoncus nisi mi, eget hendrerit nisi malesuada a. Nunc ante ante, dignissim nec augue quis, cursus venenatis lacus. Ut efficitur, magna ut faucibus semper, risus odio cursus eros, eu laoreet quam orci vel ipsum. Pellentesque sagittis tortor ac lacus dapibus lacinia. Donec convallis quam nisi, non sollicitudin odio egestas vitae. Etiam erat tellus, pellentesque at vestibulum vel, pellentesque at erat. Sed sit amet urna eu ante faucibus placerat. Maecenas a ligula et libero ultrices dignissim.
                
                Donec dictum, ante sit amet commodo sodales, est eros sollicitudin arcu, vitae facilisis enim lectus ut lorem.
    </div>
  );
};

export default Content;
